CREATE DATABASE cmsoop;
USE cmsoop;
CREATE TABLE menu (
  menu_id int AUTO_INCREMENT PRIMARY KEY,
  name varchar(100),
  content text,
  published date
);

INSERT INTO menu (name, content, published) VALUES ("Lorem ipsum dolor sit amet", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tortor dolor, suscipit ut nulla a, rhoncus scelerisque augue. Sed nisi magna, tincidunt efficitur posuere ut, tempus vel felis. Phasellus vestibulum egestas nisl. Nullam eu malesuada tellus. Mauris eu velit ac mi luctus dapibus id et sapien. Morbi malesuada sit amet elit tincidunt accumsan. Vivamus eleifend interdum turpis eget vestibulum. Fusce sagittis pellentesque pellentesque. Quisque pharetra odio sed augue tristique, ac hendrerit orci lacinia. Pellentesque rutrum, diam eget suscipit venenatis, risus nulla cursus orci, non gravida tortor dolor vel libero. Praesent in leo nec odio sollicitudin sodales. Proin egestas purus neque, in hendrerit leo lacinia sit amet. Morbi a arcu quis ligula auctor laoreet vitae a nisl. Suspendisse eu odio non nisi consequat eleifend at sed nunc. Fusce bibendum erat eros, non tincidunt quam tempus quis.

Praesent vitae pretium urna. Aliquam et nunc vitae nulla pellentesque pharetra. Mauris a diam ornare mi pellentesque venenatis. Donec suscipit, eros eu egestas imperdiet, diam justo gravida tortor, non tincidunt erat sem non lorem. Aenean venenatis iaculis mi, eget volutpat sem varius sed. Donec metus lectus, interdum eget luctus sed, tincidunt vel ante. Sed quam ante, convallis fringilla luctus vel, euismod sit amet mi. Nullam in rhoncus ante, in hendrerit nisi. Integer gravida lacus velit, sed efficitur metus tempus pulvinar.", "2020-10-25");

INSERT INTO menu (name, content, published) VALUES ("Nullam id arcu egestas", "Nulla facilisi. In ac viverra est. Nullam id arcu egestas, mattis risus id, porttitor neque. Proin ex arcu, rhoncus id lorem at, lobortis ultricies arcu. Fusce ex mauris, laoreet sed ultricies non, volutpat eget nisl. In ultricies erat lacinia felis scelerisque bibendum non eu eros. Pellentesque turpis libero, scelerisque nec urna id, dictum vulputate urna. Praesent euismod neque eget lectus condimentum, fermentum varius nunc sodales. Duis congue mattis vestibulum. Sed felis leo, pharetra eget sem eu, varius rhoncus purus.

Ut ut urna gravida, efficitur velit a, convallis magna. Donec vitae vehicula enim. Nam magna felis, consectetur eu lobortis commodo, tempor a leo. Morbi eu lectus nec tellus condimentum maximus vel non mi. Vestibulum rutrum elit eu velit pretium ultricies. Phasellus id sapien sit amet quam venenatis posuere. Donec posuere, est elementum egestas eleifend, risus felis consectetur nisl, et condimentum justo tortor rutrum dui. In euismod congue orci, non tincidunt purus pulvinar sed. Etiam eget massa sapien. Vestibulum pretium ornare lorem, at tincidunt elit mollis nec. Proin consequat mi quis egestas aliquam.

Aenean ultrices, est ac malesuada varius, felis felis pharetra velit, in dignissim lectus justo ac nibh. Donec porta, leo non convallis malesuada, sapien justo maximus sapien, nec auctor felis nulla in eros. Nunc ac ornare justo. Aliquam id erat ut enim vestibulum congue. Nam dictum, ligula et convallis tempus, ipsum magna luctus felis, sed vulputate ipsum justo sit amet arcu. Curabitur non luctus nisl, quis efficitur neque. Nulla tortor quam, luctus sit amet tortor sit amet, posuere cursus diam. Nunc semper metus eget metus tincidunt, eget mollis ex rutrum. Aliquam magna nulla, posuere rutrum condimentum vitae, maximus ac turpis. Praesent ac odio erat.", "2020-11-03");

INSERT INTO menu (name, content, published) VALUES ("Aliquam in lorem feugiat", "Donec blandit ullamcorper lorem sit amet imperdiet. Sed dignissim ut lorem a porttitor. Cras congue tortor pulvinar erat tempus imperdiet. Duis sit amet lorem eget turpis facilisis dictum. Aliquam in lorem feugiat, posuere sapien sit amet, tincidunt magna. Aenean egestas hendrerit nunc eget fermentum. Suspendisse sodales elementum fermentum. Quisque nec sapien in orci viverra eleifend nec sed quam. Etiam ut metus hendrerit quam convallis feugiat. Fusce elit mi, maximus in diam quis, tempus condimentum risus. Nulla posuere, ligula vitae semper egestas, elit orci ullamcorper nisl, at semper augue odio in risus.

Aliquam rutrum velit tortor, quis bibendum arcu laoreet in. Fusce lacinia eu nisi vitae imperdiet. Proin faucibus ac tortor id iaculis. Morbi quis pulvinar arcu. Donec imperdiet imperdiet erat, vitae facilisis mauris. Donec quis ultricies risus. Aliquam sodales tellus nec lectus consectetur, quis malesuada est ornare. Aliquam porta sed urna ac congue. Sed sodales lorem vel condimentum viverra. Ut sollicitudin porttitor elit, lacinia feugiat massa scelerisque id.

Nam sit amet maximus nulla, vel sagittis libero. Nulla posuere augue sed volutpat maximus. Nulla facilisi. Maecenas massa diam, posuere feugiat eros iaculis, cursus varius urna. Nunc blandit sem non efficitur ultrices. Vestibulum consequat turpis eget nunc dignissim, nec pellentesque nisi aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus rhoncus sollicitudin gravida. Quisque luctus volutpat porta.", "2020-12-12");